name: Build APK
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer
        sudo apt-get update
        sudo apt-get install -y python3-pip build-essential git python3 python3-dev
        sudo apt-get install -y libssl-dev
        sudo apt-get install -y libffi-dev
        sudo apt-get install -y libltdl-dev
        sudo apt-get install -y zlib1g-dev
        sudo apt-get install -y openjdk-11-jdk
        sudo apt-get install -y autoconf
        sudo apt-get install -y libtool
        sudo apt-get install -y pkg-config
        sudo apt-get install -y zip unzip
        sudo apt-get install -y curl

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug
        path: bin/*.apk 